spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf.cache: false
  datasource:
    url: jdbc:h2:~/test
    username: sa
  jpa.hibernate.ddl-auto: create-drop

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
    tacos: DEBUG

taco:
  orders:
    pageSize: 10

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 9090

logging:
  level:
    root: WARN
    org.springframework.security: WARN
    tacos: WARN