server:
  port: 9090

spring:
  thymeleaf.cache: false
  datasource:
    url: jdbc:h2:~/test
    username: sa
  jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG

taco:
  orders:
    pageSize: 10